import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <header className="bg-gray-200 p-4 ">
          <a href="/" className="logo">
            Trello-Clone
          </a>
        </header>
        <main className="p-8">{children}</main>
      </body>
    </html>
  );
}
